name: CI/CD Actions

on:
  pull_request:
    branches: [ master, feature/*, fix/* ]
  push:
    branches: [ master, feature/*, fix/* ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0'
          cache: 'nuget'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run unit tests
        run: dotnet test